### ISSUE TITLE
App crashes when attempting to play podcasts

### ISSUE THREAD

**Issue by sam-mininberg** [rasmuslos/ShelfPlayer#200]
Audiobookshelf v2.18.1 (Docker)
ShelfPlayer v2.5.2 (iOS App Store)

App immediately crashes after clicking play on any podcast. Playback works from Audiobookshelf webapp. Crash report attached.

[ShelfPlayer-2025-01-23-120331.ips.txt](https://github.com/user-attachments/files/18524400/ShelfPlayer-2025-01-23-120331.ips.txt)

**Comment by thrillho** [comment]
I'm having the same issue, same version numbers, although I am running on ABS v2.18.1 on Debian.

**Comment by Migz93** [comment]
I'm also having the same issue. Only with Audiobookshelf v2.18.0 or v2.18.1, I rolled back to v2.17.7 and the issue went away.
Not sure if a bug on Audiobookshelf side or something that was just updated that side and now needs to be reflected in ShelfPlayer.

**Comment by floenz** [comment]
Same versions as above, also crashing.

**Comment by Unlearned6688** [comment]
Same as above. The app put out by ABS devs directly works for podcasts, as does the webapp. Audiobooks plays in either version.

**Comment by spuft123** [comment]
Same experience with podcasts using ShelfPlayer 2.5.2 (iOS) and Audiobookshelf v2.18.1 (Docker).

**Comment by rasmuslos** [comment]
Playing podcasts, using both the button on the podcast and episode view works fine for me, using `2.5.2` and `2.18.1`. Is there anything that you can think of that might be causing the issue. What devices (specific models) are you using? [Is anyone else able to provide a crash log.](https://help.apple.com/xcode/mac/current/#/dev0f3181c2c) The one @sam-mininberg provided sadly didn't contain much useful information, extracting it is as much work as just continuing #189.

Speaking of which, this may be caused by a concurrency issue (at least that is what I would guess based on the limited information from the crash log), so this might also be solved with #189. It is really strange that rolling back ABS fixed the issue, especially since it's working fine for me.

**Comment by sam-mininberg** [comment]
I just re-updated Audiobookshelf to 2.18.1 after reverting to 2.17.7 earlier this week, and playback is working fine now. If I start seeing crashes again, I'll run the app on my iPhone via Xcode in the hope of providing a more-useful error message.

**Comment by Unlearned6688** [comment]
> Playing podcasts, using both the button on the podcast and episode view works fine for me, using `2.5.2` and `2.18.1`. Is there anything that you can think of that might be causing the issue. What devices (specific models) are you using? [Is anyone else able to provide a crash log.](https://help.apple.com/xcode/mac/current/#/dev0f3181c2c) The one [@sam-mininberg](https://github.com/sam-mininberg) provided sadly didn't contain much useful information, extracting it is as much work as just continuing [#189](https://github.com/rasmuslos/ShelfPlayer/issues/189).
> 
> Speaking of which, this may be caused by a concurrency issue (at least that is what I would guess based on the limited information from the crash log), so this might also be solved with [#189](https://github.com/rasmuslos/ShelfPlayer/issues/189). It is really strange that rolling back ABS fixed the issue, especially since it's working fine for me.

Here's some logs. It still crashes for me trying to play a bunch of different podcasts (but some don't crash...). I didn't experiment a whole lot seeing what does/doesn't crash, but it *appeared* at a glance that podcasts I had manually added (downloaded then added to directories that ABS looks in) would crash. But podcasts that automatically downloaded from like "the normal source" (not me adding them) were more ok or all ok.

Again, the pods and audiobooks all play fine in the ABS app from the ABS dev team as well as the webplayer.

Hopefully these logs and info help.

https://paste.mozilla.org/5xxX0Yf3
https://paste.mozilla.org/wFVK6RmW
https://paste.mozilla.org/zczhKtze
https://paste.mozilla.org/mLVUSUXQ
https://paste.mozilla.org/RubD6eow
https://paste.mozilla.org/kfCGWv9Y
https://paste.mozilla.org/6ugQkC9t

ABS docker version 2.18.1
ShelfPlayer 2.5.2 (528)
Database: 1.1.0 (ShelfPlayer)

iPhone 16 Pro - iOS 18.3
iPad Pro 11" 3rd Gen (M1 Chip) - iPadOS 18.3
(Both crash)

**Comment by slyfoxgh** [comment]
Same problem. All podcasts crash when trying I press play. How do I find the crash report to share?

**Comment by Unlearned6688** [comment]
> Same problem. All podcasts crash when trying I press play. How do I find the crash report to share?

rasmuslos provided the link above, but here it is again

https://help.apple.com/xcode/mac/current/#/dev0f3181c2c

If you have access to Windows just load iTunes

 go to your phone or iPad inside iTunes (click the little device symbol)

sync it with your device (click the "sync" button. Bottom right corner of the application)

Go to the directory ```C:\Users\<user_name>\AppData\Roaming\Apple computer\Logs\CrashReporter/MobileDevice``` username is your local Windows username. Usually it's a shortened form of whatever your email for your Microsoft account is that you log in with. 

And you'll see a bunch of files. Find the ones called something like "ShelfPlayer-somethingsomething.ips"

GitHub doesn't allow uploading .ips file type (......) which is why I copied them into a pastebin-style site. (Please god don't copy the entire giant file directly as text)

**Comment by rasmuslos** [comment]
The problem with these debug logs is that they are not symbolicated. That means that they only include the byte offset of the instructions. It's possible to add the actual method names, etc. back, but I admittedly have never done that and I don't have the necessary source maps (but I think I uploaded them to the AppStore, so they are somewhere), but figuring this out, especially because the relevant code is already gone and replaced for 2.6.0, is not something on my agenda...

But both crash logs show that the crash occurred on a background (not thread 0) thread. This at least indicated, that this is merely a concurrency issue, which should be fixed in 2.6.0.

**Comment by rasmuslos** [comment]
I received an E-Mail describing a similar problem, and the author noted that this issue might be related to the date of the podcast / episode, can you confirm this?

**Comment by rasmuslos** [comment]
Another wild guess I had while rewriting the AudioPlayer: try disabling "queue podcast episodes" in the settings app, arrays are not thread safe in swift, and queuing the next episodes might cause the issue.

**Comment by Rolgan4** [comment]
I'm having issues with this and just tried disabling the "queue podcast episodes" and it didn't change anything for me.

I did notice that it seems to be caused by files that weren't downloaded by audiobookshelf, ie i have lots of files i have previously downloaded and added into audiobookshelf these all crash as soon as you try to play or download but i matched one of the podcasts with its current rss feed and downloaded the latest episode and this works (also tried adding a new podcast and downloading an episode and this worked)

hope this helps

**Comment by trungpd56** [comment]
I got this problem as well. It work fine if the podcast is downloaded by the abs app. If i add podcast from another source, it crashed immediately

**Comment by rasmuslos** [comment]
#210 might have fixed this, please check in a few days when version `2.5.3` came through app review.

**Comment by Migz93** [comment]
2.5.3 appears to have resolved the issue for me. I've now updated audiobookshelf to the latest v2.19.4 and I can play again with no crashing.

**Comment by Rolgan4** [comment]
Just checked and yep 2.5.3 update has fixed it, Thanks @rasmuslos
